<?php
/**
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2021 Adyen N.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
?>
<script>
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            layout([
                {
                    component: 'Adyen_Payment/js/view/payment/method-renderer/multishipping/adyen-hpp-method',
                    // TODO multishipping made a change for testing purposes only,
                    //  include all the methods here as now it only includes amazonpay
                    name: 'payment_method_adyen_amazonpay',
                    method: 'adyen_amazonpay',
                    item: { method: 'adyen_amazonpay' }
                }
            ]);
            $('body').trigger('contentUpdated');
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
